const Imaages = {
    logo: require('../assets/img/logo/logo.png'),
    Account: require('../assets/img/account/account.png'),
    Catalog: require('../assets/img/catalog/catalog.png'),
    Home: require('../assets/img/home/home.png'),
    Like: require('../assets/img/like/like.png'),
    Notifications: require('../assets/img/notification/notification.png'),
    Profile: require('../assets/img/profile/profile.png'),
    Search: require('../assets/img/search/search.png'),
    Favlike: require('../assets/img/likeFav/likeFav.png'),
    password: require('../assets/img/password/password.png'),
    leftIcon: require('../assets/img/leftIcon/leftIcon.png'),
    newLogo: require('../assets/img/newLogo/newLogo.png'),
    crossIcons: require('../assets/img/crossIcon/crossIcon.png'),
    loginBg: require('../assets/img/loginBg/loginBg.png'),
    menu: require('../assets/img/menu/menu.png'),
    onBoarding: require('../assets/img/Onboarding/Onboarding.png'),
    rightArrow: require('../assets/img/rightArrow/rightArrow.png'),
    schoolIcon: require('../assets/img/schoolIcon/schoolIcon.png'),
    setting: require('../assets/img/setting/setting.png'),
    classes:require('../assets/img/class/class.png'),
    openEye:require('../assets/img/eyeOpen/eyeOpen.png'),
    edit:require('../assets/img/edit/edit.png'),
    leftIcons:require('../assets/img/leftArrow/leftArrow.png'),
    deleteIcons:require('../assets/img/delete/delete.png'),
    dropIcon:require('../assets/img/dropIcon/dropIcon.png'),
    threeDots:require('../assets/img/threeDots/threeDots.png'),
    CameraImages:require('../assets/img/cameras/cameras.png')

}
export default Imaages